### ISSUE TITLE
unable to download .txt file in second time

### ISSUE THREAD

**Issue by priyeshgpt** [satyamsovan123/sanfoundry-dl#2]
this could be only my issue, but when i download and run the program first time it works fine....but after deleting the "result" txt file....and re-trying to download other set of mcq it doesnt work.

the error i am getting is:

PS D:\Software download\sanfoundry-dl-master> & C:/Users/hp/AppData/Local/Programs/Python/Python39/python.exe "d:/Software download/sanfoundry-dl-master/main.py"    
Traceback (most recent call last):
  File "d:\Software download\sanfoundry-dl-master\main.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
PS D:\Software download\sanfoundry-dl-master>

**Comment by satyamsovan123** [comment]
I believe it's the requests module that is making all the ruckus. You can do **pip install requests** before executing **python3 main.py**
