### ISSUE TITLE
unable to download

### ISSUE THREAD

**Issue by aziyamehboob** [satyamsovan123/sanfoundry-dl#23]
i was trying to download and followed the instructions given.but unable to download 
![snip](https://user-images.githubusercontent.com/6000110/183241487-0b4c2632-ffbb-44ad-a0cd-09cc0986c2bd.PNG)

**Comment by ahsanazam166** [comment]
1) its driver issue, here are two drivers for windows and linux.
[chromedriver_linux64.zip](https://github.com/satyamsovan123/sanfoundry-dl/files/9313663/chromedriver_linux64.zip)
[chromedriver_win32.zip](https://github.com/satyamsovan123/sanfoundry-dl/files/9313664/chromedriver_win32.zip)
2) manually add the window/linux driver under sanfoundry-dl/api/main/service/scrappers/get_questions_answers/get_questions_answers.py
3) kindly go through the code and uncomment the manual driver location path, file(get_questions_answers.py), line(37-39)
4) make sure you have commented the automatic driver locations, file(get_questions_answers.py), line(45-46)
5) NOTE. some urls from the website "https://www.sanfoundry.com/" not working properly.
![pic](https://user-images.githubusercontent.com/107205577/184286321-39f58869-fd67-47c5-b1d0-76fefce83b33.jpeg)

**Comment by satyamsovan123** [comment]
These instructions are already there in he readme file. The URLs with “1000” in the it will work.
